### ISSUE TITLE
add some pictures ? idk it looks good 

### ISSUE THREAD

**Issue by SpaceCypher** [nexxeln/spotify-voice-control#5]

**Comment by nexxeln** [comment]
hi!
could you please clarify on what pictures exactly? are you suggesting screenshots or some kind of demo video, or pictures within the actual program?

**Comment by SpaceCypher** [comment]
i am suggesting that screenshots would be good

**Comment by nexxeln** [comment]
i have though about doing a demo video at some point. but there are still some features i would like to add before making the video so that i can show the full functionality.
but yeah for now i'll add some screenshots for sure. thanks for the suggestion!

**Comment by SpaceCypher** [comment]
yeah no problem!

**Comment by nexxeln** [comment]
i added some gifs. check it out!
tell me if there's something you feel can be changed here

**Comment by SpaceCypher** [comment]
yep 👍🏻 its good

**Comment by nexxeln** [comment]
alright thank you!
